# Actividad 1 - Módulo 3
## Obtención y preparación de datos

### Ejercicio 1
Crear un vector con valores dentro del rango 10 a 49.

In [1]:
import numpy as np

In [33]:
vector = np.arange(10,50,1)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Ejercicio 2
Invertir el vector anterior

In [34]:
vector_inv = vector[-1::-1]
print(vector_inv)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Ejercicio 3
Crear una matriz con valores de 0 a 8

In [4]:
matriz = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Ejercicio 4
Encontrar los índices que no son 0 en el arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [5]:
vector = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
nonzeros = np.arange(len(vector))[vector>0]
print(f"Los indices de los valores que no son ceros en el vector son {nonzeros}")

Los indices de los valores que no son ceros en el vector son [ 0  1  2  3  4  6 10 11 12 13 14]


### Ejercicio 5
Crear una matriz identidad de 6x6


In [6]:
id = np.eye(6)
print(id)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Ejercicio 6
Crear una matriz con valores al azar con forma 3x3x3

In [7]:
hypermatrix = np.random.rand(3,3,3)
print(hypermatrix)

[[[0.68923072 0.32643278 0.03871314]
  [0.57619037 0.07180832 0.22560716]
  [0.99479136 0.27508012 0.17642685]]

 [[0.67184353 0.59680121 0.24112655]
  [0.43555346 0.92442303 0.91569422]
  [0.33079487 0.08775491 0.8568204 ]]

 [[0.31772883 0.13677495 0.0999311 ]
  [0.83844047 0.31177866 0.60718112]
  [0.15746789 0.92628804 0.88832888]]]


### Ejercicio 7
Crea un arreglo NumPy de tamaño 5x5 lleno de ceros.

In [8]:
ceros = np.zeros((5,5))
print(ceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ejercicio 8
Crea un arreglo NumPy de tamaño 3x3 lleno de unos.

In [9]:
unos = np.ones((3,3))
print(unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Ejercicio 9
Crea dos arreglos NumPy de tamaño 2x2 con valores aleatorios. Realiza
la suma, resta, multiplicación y división de los arreglos creados.

In [40]:
# Creación de vectores aleatorios(de enteros para facilitar lectura)
ran1 = np.random.randint(1,100, size = (2,2))
ran2 = np.random.randint(1,100, size = (2,2))

# Operaciones pedidas
print(f"Suma: {ran1 + ran2}\n")
print(f"Resta: {ran1 - ran2}\n")
print(f"Multiplicación: {ran1 * ran2}\n")
print(f"División: {ran1 / ran2}")

Suma: [[ 86  79]
 [156  95]]

Resta: [[-60 -43]
 [-22  53]]

Multiplicación: [[ 949 1098]
 [5963 1554]]

División: [[0.17808219 0.29508197]
 [0.75280899 3.52380952]]


### Ejercicio 10
Crea un vector con valores entre 0 y 10, con intervalos de 0.5.

In [39]:
vec = np.arange(0,10.1,.5)
print(vec)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


### Ejercicio 11
Genera una matriz de tamaño 5x5 con valores aleatorios enteros
entre 1 y 100.

In [12]:
rand_mat = np.random.randint(1, 101, size=(5,5))
print(rand_mat)

[[ 59  99  33  42  39]
 [  2   6  39  41  31]
 [ 39  42  51  90  35]
 [ 13  20  49  54  44]
 [ 59  46   7 100  45]]


### Ejercicio 12
Crea un arreglo NumPy unidimensional de 10 elementos.

In [41]:
vec = np.array(range(10))
print(vec)

[0 1 2 3 4 5 6 7 8 9]


### Ejercicio 13
Imprime el primer elemento del arreglo anterior.

In [42]:
print(vec[0])

0


### Ejercicio 14
Imprime los últimos 3 elementos del arreglo anterior.

In [46]:
print(vec[7:])

[7 8 9]


### Ejercicio 15
Imprime los elementos del índice 3 al 7 anterior.

In [47]:
print(vec[2:7])

[2 3 4 5 6]


### Ejercicio 16
Cambia el valor del índice 5 por 20 en el arreglo anterior.

In [17]:
vec[4] = 20
print(vec)

[ 0  1  2  3 20  5  6  7  8  9]


### Ejercicio 17
Crea un arreglo NumPy con números del 1 al 10.

In [18]:
arreglo = np.arange(1,11)
print(arreglo)

[ 1  2  3  4  5  6  7  8  9 10]


### Ejercicio 18
Calcula la suma, el promedio, la desviación estándar y el máximo
valor del arreglo del ejercicio anterior.

In [19]:
# Suma
suma = np.sum(arreglo)
print(f"La suma del arreglo es {suma}.")

# Promedio
avg = np.mean(arreglo)
print(f"El promedio del arreglo es {avg}")

# Desviación estandar
d_e = np.std(arreglo)
print(f"La desviación estándar del arreglo es {d_e}")

# Máximo
M = np.max(arreglo)
print(f"El máximo del arreglo es {M}")

La suma del arreglo es 55.
El promedio del arreglo es 5.5
La desviación estándar del arreglo es 2.8722813232690143
El máximo del arreglo es 10


### Ejercicio 19
Crear un arreglo con elementos del 1 al 10 y seleccionar solo los pares.

In [48]:
arreglo = np.array(range(1,11))
pares = arreglo[arreglo%2 == 0]
print(f"Los números pares del arreglo son {pares}")

Los números pares del arreglo son [ 2  4  6  8 10]


### Ejercicio 20
Calcula la suma, la media, el máximo y el mínimo de los valores de
seno, coseno y tangente para un conjunto de ángulos en grados dados por [0, 30, 45, 60, 90].

In [59]:
arreglo = np.radians([0, 30, 45, 60, 90])

# Funciones del arreglo
func = {"Seno": "","Coseno": "","Tangente":""}
func["Seno"] = np.sin(arreglo)
func["Coseno"] = np.cos(arreglo)
func["Tangente"] = np.tan(arreglo)

# Despliegue de valores por lista
for funcion, vec in func.items():
    print(f"{funcion}---------------------------")
    print(f"La suma del {funcion} del arreglo es {np.sum(vec)}.")
    print(f"La media del {funcion} del arreglo es {np.median(vec)}.")
    print(f"La máximo del {funcion} del arreglo es {np.max(vec)}.")
    print(f"La mínimo del {funcion} del arreglo es {np.min(vec)}.\n")


Seno---------------------------
La suma del Seno del arreglo es 3.0731321849709863.
La media del Seno del arreglo es 0.7071067811865476.
La máximo del Seno del arreglo es 1.0.
La mínimo del Seno del arreglo es 0.0.

Coseno---------------------------
La suma del Coseno del arreglo es 3.0731321849709863.
La media del Coseno del arreglo es 0.7071067811865476.
La máximo del Coseno del arreglo es 1.0.
La mínimo del Coseno del arreglo es 6.123233995736766e-17.

Tangente---------------------------
La suma del Tangente del arreglo es 1.6331239353195374e+16.
La media del Tangente del arreglo es 0.9999999999999999.
La máximo del Tangente del arreglo es 1.633123935319537e+16.
La mínimo del Tangente del arreglo es 0.0.



### Ejercicio 21
Crea un arreglo NumPy de tamaño 4x4 con valores del 1 al 16.

In [22]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Ejercicio 22
Convierte el arreglo anterior en una matriz de 2x8.

In [23]:
arr = arr.reshape(2,8)
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


### Ejercicio 23
Obtén la transpuesta de la matriz anterior.

In [24]:
arrT = arr.T
print(arrT)

[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]


### Ejercicio 24
Redimensiona la matriz anterior a una de 2x2x4.

In [25]:
hyp_arr = arrT.reshape(2,2,4)
print(hyp_arr)

[[[ 1  9  2 10]
  [ 3 11  4 12]]

 [[ 5 13  6 14]
  [ 7 15  8 16]]]


### Ejercicio 25 - **Máquina de monedas**
Para despachar dinero en efectivo con una máquina automática realice lo
siguiente:

1. Escriba una función separanum(valor), que reciba un valor numérico real y
separe las cantidades en un vector que contiene:
centavos, unidades, decenas, centenas, etc. Los centavos equivalen a usar
dos decimales redondeado al entero más cercano.
Desarrolle el algoritmo usando operaciones de cociente y residuo (no use
round()).

In [60]:
import pandas as pd

In [27]:
# Parte 1
def separanum(valor):
    # Extraer decimales
    valor = str(valor).split(".")
    ent = int(valor[0])
    dec = valor[1]
    if len(dec)>2:
        if int(dec[2])<5:
            cantidades = [int(dec[0:2])]
        else:
            cantidades = [int(dec[0:2]) + 1]
    else:
        cantidades = int(dec)
    # Separar parte entera de valor
    while ent !=0:
        ent, res = divmod(ent,10)
        cantidades.append(res)
    # Despliegue grafico solo si valor < 1000
    if len(cantidades)>4:
        return cantidades
    else:
        label = ["Centavos", "Unidades", "Decenas", "Centenas"]
        dict = {}
        for i, num in enumerate(cantidades):
            dict[label[i]] = [num]
        return pd.DataFrame(dict)


In [28]:
# Test de la funcion separanum
# Número mayor a 1000
print(separanum(1000.155))
# Número menor a 1000
separanum(3.1415)

[16, 0, 0, 0, 1]


Centavos  Unidades
0        14         3

2. Realice una función cuantas monedas(centavos) que reciba la
cantidad de centavos a entregar con monedas de 1, 5, 10, 25, 50
centavos usado la menor cantidad de monedas.

In [29]:
# Parte 2
def cuenta_monedas(centavos):
    valores = ["50", "25", "10", "5", "1"]
    monedas = {}
    for i in valores:
        cant, centavos = divmod(centavos, int(i))
        monedas[i] = [cant]
    return pd.DataFrame(monedas)

In [30]:
# Test de la funcion cuenta_monedas
centavos = 99
print(f"Las monedas optimas para entregar {centavos} está dada por:")
cuenta_monedas(99)

Las monedas optimas para entregar 99 está dada por:


50  25  10  5  1
0   1   1   2  0  4

### Ejercicio 26 - **Creación de un calendario**
Realice un programa que permita crear un calendario de un mes cualquiera,
conociendo el día de la semana que inicia el mes y el número de días que
tiene el mes.

In [31]:
def calendario(inicio, dias):
    import numpy as np
    import pandas as pd

    nombres = ("D", "L", "M", "X", "J", "V", "S")
    semanas = [np.zeros(7)]
    semanas[0][inicio-1:] = np.arange(1,(8-inicio+1))

    dias_rest = dias - semanas[0][-1]
    semana = 0
    row = ["Semana " + str(semana+1)]

    while dias_rest >=7:
        semanas.append(np.arange(semanas[semana][-1] + 1, semanas[semana][-1] + 8))
        dias_rest = dias - semanas[semana+1][-1]
        semana += 1
        row.append("Semana " + str(semana+1))


    if dias_rest != 0:
        semanas.append(np.zeros(7))
        semanas[semana+1][:int(dias_rest)] = np.arange(semanas[semana][-1] + 1, dias + 1)
        row.append("Semana " + str(semana+2))

    return pd.DataFrame(np.array(semanas), columns=nombres, index=row, dtype = int)

In [32]:
# Test función anterior
print("El calendario del presente mes de febrero queda dado por:")
calendario(5,29)

El calendario del presente mes de febrero queda dado por:


D   L   M   X   J   V   S
Semana 1   0   0   0   0   1   2   3
Semana 2   4   5   6   7   8   9  10
Semana 3  11  12  13  14  15  16  17
Semana 4  18  19  20  21  22  23  24
Semana 5  25  26  27  28  29   0   0